title: My Documentation Site
theme: minima
# The following line is optional but helps if things don't show up
header_pages:
  - index.md
  - Aurkibidea.md
  - dillinger_sample.md
  - Markatze_lengoaiak.md
  - Sareen_planifikazioa.md
  - Sistema_eragileak.md
  - Digitalizazioa.md
  - Data_base.md
